---
- name: Installer les dépendances
  apt:
    name: "{{ item }}"
  loop:
    - "apt-transport-https"
    - "ca-certificates"
    - "curl"
    - "gnupg2"
    - "software-properties-common"

- name: Ajouter la clef du dépôt APT de Docker.
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/debian/gpg

- name: Ajouter le dépôt de Debian stable
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian buster stable"
    update_cache: true

- name: Installer le paquet de docker
  apt:
    name: "{{ item }}"
  loop:
    - "docker-ce"
    - "docker-compose"
    - "python3-docker"
